package event.management.persistance;
// Generated 3 Mar, 2016 3:49:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * BProductDetails generated by hbm2java
 */
public class BProductDetails  implements java.io.Serializable {


     private String productId;
     private String productName;
     private BigDecimal productPrice;
     private String productType;
     private byte[] productImage;
     private String fileName;

    public BProductDetails() {
    }

	
    public BProductDetails(String productId, String productName, BigDecimal productPrice, String productType, byte[] productImage) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productType = productType;
        this.productImage = productImage;
    }
    public BProductDetails(String productId, String productName, BigDecimal productPrice, String productType, byte[] productImage, String fileName) {
       this.productId = productId;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productType = productType;
       this.productImage = productImage;
       this.fileName = fileName;
    }
   
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }
    public String getFileName() {
        return this.fileName;
    }
    
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }




}


