package event.management.persistance;
// Generated 3 Mar, 2016 3:49:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ProductDetails generated by hbm2java
 */
public class ProductDetails  implements java.io.Serializable {


     private String productId;
     private String productName;
     private BigDecimal productPrice;
     private String productType;
     private byte[] productImage;
     private String imageName;
     private String productDesc;
     private String sellername;

    public ProductDetails() {
    }

	
    public ProductDetails(String productId, String productName, BigDecimal productPrice, String productType, byte[] productImage, String imageName, String productDesc) {
        this.productId = productId;
        this.productName = productName;
        this.productPrice = productPrice;
        this.productType = productType;
        this.productImage = productImage;
        this.imageName = imageName;
        this.productDesc = productDesc;
    }
    public ProductDetails(String productId, String productName, BigDecimal productPrice, String productType, byte[] productImage, String imageName, String productDesc, String sellername) {
       this.productId = productId;
       this.productName = productName;
       this.productPrice = productPrice;
       this.productType = productType;
       this.productImage = productImage;
       this.imageName = imageName;
       this.productDesc = productDesc;
       this.sellername = sellername;
    }
   
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductType() {
        return this.productType;
    }
    
    public void setProductType(String productType) {
        this.productType = productType;
    }
    public byte[] getProductImage() {
        return this.productImage;
    }
    
    public void setProductImage(byte[] productImage) {
        this.productImage = productImage;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getProductDesc() {
        return this.productDesc;
    }
    
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }
    public String getSellername() {
        return this.sellername;
    }
    
    public void setSellername(String sellername) {
        this.sellername = sellername;
    }




}


