package event.management.persistance;
// Generated 3 Mar, 2016 3:49:27 PM by Hibernate Tools 4.3.1



/**
 * UserProductDetailsId generated by hbm2java
 */
public class UserProductDetailsId  implements java.io.Serializable {


     private String userName;
     private String userEmail;
     private String productId;

    public UserProductDetailsId() {
    }

    public UserProductDetailsId(String userName, String userEmail, String productId) {
       this.userName = userName;
       this.userEmail = userEmail;
       this.productId = productId;
    }
   
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getUserEmail() {
        return this.userEmail;
    }
    
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail;
    }
    public String getProductId() {
        return this.productId;
    }
    
    public void setProductId(String productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UserProductDetailsId) ) return false;
		 UserProductDetailsId castOther = ( UserProductDetailsId ) other; 
         
		 return ( (this.getUserName()==castOther.getUserName()) || ( this.getUserName()!=null && castOther.getUserName()!=null && this.getUserName().equals(castOther.getUserName()) ) )
 && ( (this.getUserEmail()==castOther.getUserEmail()) || ( this.getUserEmail()!=null && castOther.getUserEmail()!=null && this.getUserEmail().equals(castOther.getUserEmail()) ) )
 && ( (this.getProductId()==castOther.getProductId()) || ( this.getProductId()!=null && castOther.getProductId()!=null && this.getProductId().equals(castOther.getProductId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserName() == null ? 0 : this.getUserName().hashCode() );
         result = 37 * result + ( getUserEmail() == null ? 0 : this.getUserEmail().hashCode() );
         result = 37 * result + ( getProductId() == null ? 0 : this.getProductId().hashCode() );
         return result;
   }   


}


