package event.management.persistance;
// Generated 3 Mar, 2016 3:49:27 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * UserProductDetails generated by hbm2java
 */
public class UserProductDetails  implements java.io.Serializable {


     private UserProductDetailsId id;
     private String status;
     private Date bookDt;
     private BigDecimal productPrice;
     private String productName;

    public UserProductDetails() {
    }

	
    public UserProductDetails(UserProductDetailsId id, String status, Date bookDt, String productName) {
        this.id = id;
        this.status = status;
        this.bookDt = bookDt;
        this.productName = productName;
    }
    public UserProductDetails(UserProductDetailsId id, String status, Date bookDt, BigDecimal productPrice, String productName) {
       this.id = id;
       this.status = status;
       this.bookDt = bookDt;
       this.productPrice = productPrice;
       this.productName = productName;
    }
   
    public UserProductDetailsId getId() {
        return this.id;
    }
    
    public void setId(UserProductDetailsId id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getBookDt() {
        return this.bookDt;
    }
    
    public void setBookDt(Date bookDt) {
        this.bookDt = bookDt;
    }
    public BigDecimal getProductPrice() {
        return this.productPrice;
    }
    
    public void setProductPrice(BigDecimal productPrice) {
        this.productPrice = productPrice;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }




}


